checks:
  versions: False
  required_workflows:
    backport.yaml: False
    clean.yaml: False
    audit.yaml: False

publish:
  docker:
    images:
      - name: sbrunner/scan-to-paperless
        tags:
          - '{version}'
          - '{version}-all'
