---
name: Clean docker hub tags

on: delete

jobs:
  clean:
    runs-on: ubuntu-20.04
    name: Clean docker hub tags
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - run: python3 -m pip install --user c2cciutils

      - name: Clean docker hub tags
        run: c2cciutils-clean
